version: '3'
services:
  skinsight-frontend:
    container_name: skinsight-frontend
    image: ghcr.io/florentkaram/skinsight-frontend/skinsight-frontend:latest
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.frontend-skinsight.entrypoints: websecure
      traefik.http.routers.frontend-skinsight.tls: true
      traefik.http.routers.frontend-skinsight.rule: Host(`sample-restaurant.com`) || Host(`www.sample-restaurant.com`)
    networks:
      - skinsight-frontend
networks:
  skinsight-frontend:
    external : true